program = "#",PROGRAM_ARGUMENTS,BLOCK;
PROGRAM_ARGUMENTS = ARG,{',',ARG};
ARG = ('out' | 'in'), TYPE, IDENTIFIER , | 'opt', OPTION, INT;
OPTION = 'width'|'height'|'steps';
BLOCK = { STATEMENT };
TYPE = float | int | bool | vec2 | vec3 | vec4;
STATEMENT = ( |ASSIGNMENT |DECLARATION|WHILE | IF | FUNC_DEF | RETURN ), "\n" ;
FUNC_DEF ="function", IDENTIFIER, "(", ( | IDENTIFIER, { ( "," ), IDENTIFIER } ), ")", "\n", { ( STATEMENT ) }, "end";
FUNC_CALL = IDENTIFIER, "(", , ( | BOOL_EXP, { ( "," ), BOOL_EXP } ),")";
WHILE = "while", BOOL_EXP, "do", "\n", { ( STATEMENT )}, "end";
IF = "if", BOOL_EXP, "then", "\n", { ( STATEMENT )}, (  | ( "else", "\n",  { ( STATEMENT )})), "end" ;
ASSIGNMENT = IDENTIFIER, '=', BOOL_EXP;
DECLARATION = 'local', IDENTIFIER,('=', BOOL_EXP | );
RETURN = "return", BOOL_EXP;
BOOL_EXP = BOOL_TERM, { ("or"), BOOL_TERM } ;
BOOL_TERM = REL_EXP, { ("and"), REL_EXP } ;
REL_EXP = EXPRESSION, { ("==" | ">" | "<"), EXPRESSION } ;
EXPRESSION = TERM, {("+" | "-" | "**"), TERM};
TERM = FACTOR, { ("*" | "/"), FACTOR } ;
FACTOR = INT | IDENTIFIER | FLOAT | vec2 | vec3 | vec4 | (("+" | "-" | "not"), FACTOR ) | "(", EXPRESSION, ")"| FUNCTION_CALL ;
vec2 = 'vec2','(',FLOAT,',',FLOAT,')';
vec3 = 'vec3','(',FLOAT,',',FLOAT,',',FLOAT,')';vec4 = 'vec4','(',FLOAT,',',FLOAT,',',FLOAT,')';
IDENTIFIER = LETTER, { LETTER | DIGIT | "_" }, (PROPERTY_ACCESS |);
PROPERTY_ACCESS = '.', ('x'|'y'|'z'|'w');
INT =  DIGIT, { DIGIT };
FLOAT = INT,'.',INT;
LETTER = ( "a" | "..." | "z" | "A" | "..." | "Z" );
FUNCTION_CALL = IDENTIFIER,'(',{IDENTIFIER,','},')';
